const legoData = [
  {
    "namn": "Stranger Things: The Creel House",
    "id": "11370",
    "skick": "",
    "Filer media": "./attachments/11370.jpg",
    "Kategori": "Icons",
    "Tema": "Stranger Things",
    "delar": "2593",
    "Released": "2026",
    "minifigures": "13",
    "byggat": ""
  },
  {
    "namn": "Red Panda Mei",
    "id": "40798",
    "setID": "50827",
    "skick": "",
    "Filer media": "./attachments/40798.jpg",
    "Kategori": "BrickHeadz",
    "Tema": "Disney",
    "delar": "121",
    "Released": "2025",
    "minifigures": "0",
    "byggat": ""
  },
  {
    "namn": "Thanksgiving Turkey",
    "id": "40273",
    "setID": "27874",
    "skick": "",
    "Filer media": "./attachments/40273.jpg",
    "Kategori": "BrickHeadz",
    "Tema": "Seasonal",
    "delar": "114",
    "Released": "2018",
    "minifigures": "0",
    "byggat": ""
  },
  {
    "namn": "Easter Sheep",
    "id": "40380",
    "setID": "29653",
    "skick": "",
    "Filer media": "./attachments/40380.jpg",
    "Kategori": "BrickHeadz",
    "Tema": "Seasonal",
    "delar": "192",
    "Released": "2020",
    "minifigures": "0",
    "byggat": ""
  },
  {
    "namn": "Halloween Witch",
    "id": "40272",
    "setID": "27873",
    "skick": "",
    "Filer media": "./attachments/40272.jpg",
    "Kategori": "BrickHeadz",
    "Tema": "Seasonal",
    "delar": "151",
    "Released": "2018",
    "minifigures": "0",
    "byggat": ""
  },
  {
    "namn": "Easter Bunny",
    "id": "40271",
    "setID": "27872",
    "skick": "",
    "Filer media": "./attachments/40271.jpg",
    "Kategori": "BrickHeadz",
    "Tema": "Seasonal",
    "delar": "126",
    "Released": "2018",
    "minifigures": "0",
    "byggat": ""
  },
  {
    "namn": "Lucky Cat",
    "id": "40436",
    "setID": "29654",
    "skick": "",
    "Filer media": "./attachments/40436.jpg",
    "Kategori": "BrickHeadz",
    "Tema": "Seasonal",
    "delar": "134",
    "Released": "2020",
    "minifigures": "0",
    "byggat": ""
  },
  {
    "namn": "Elphaba & Glinda Figures",
    "id": "40794",
    "setID": "51589",
    "skick": "",
    "Filer media": "./attachments/40794.jpg",
    "Kategori": "BrickHeadz",
    "Tema": "Wicked",
    "delar": "325",
    "Released": "2025",
    "minifigures": "0",
    "byggat": ""
  },
  {
    "namn": "Black Widow",
    "id": "41591",
    "setID": "27015",
    "skick": "",
    "Filer media": "./attachments/41591.jpg",
    "Kategori": "BrickHeadz",
    "Tema": "Marvel Super Heroes",
    "delar": "143",
    "Released": "2017",
    "minifigures": "0",
    "byggat": ""
  },
  {
    "namn": "Harry, Hermione, Ron & Hagrid",
    "id": "40495",
    "setID": "30934",
    "skick": "",
    "Filer media": "./attachments/40495.jpg",
    "Kategori": "BrickHeadz",
    "Tema": "Wizarding World",
    "delar": "466",
    "Released": "2021",
    "minifigures": "0",
    "byggat": ""
  }
];